### ISSUE TITLE
YourFlyouts brightness slider shows current volume, then current brightness slider, but volume number stays when at 0 brightness

### ISSUE THREAD

**Issue by Aegim** [Jax-Core/YourFlyouts#10]
(Apologies for showing up so frequently). The issue mentioned above does not interfere with brightness and is simply to do with appearance. This minor issue specifically occurs when brightness is set to 0, so the only reason to press the brightness ↓ key is to check the brightness. Other than that, the brightness symbol still shows up. I'm likely a bother with how many issues I have submitted, but is there a way to show a value for the brightness slider using YourFlyouts? 

Best Regards!

(This screenshot is from pressing the brightness key, but brightness is set to 0)
![Screenshot (4478)](https://user-images.githubusercontent.com/111807698/187108510-21b0894e-ac29-4d24-914b-84ea89825f56.png)
(Second press (pressing x amount more shows the same flyout))
![Screenshot (4479)](https://user-images.githubusercontent.com/111807698/187108514-245bebba-32ed-4544-9252-0c2c032b0c9d.png)
(Pressing brightness ↑)
![Screenshot (4480)](https://user-images.githubusercontent.com/111807698/187108517-85d44cd8-81c7-4c62-8c52-efce532b8e14.png)

**Comment by EnhancedJax** [comment]
Thanks for reporting. This will be fixed in the next update.

**Comment by Aegim** [comment]
I've already mentioned it over on Discord, but I should've told you when opening the issue that the slider will not function at all when pressing Volume Down. Sorry about that!

**Comment by EnhancedJax** [comment]
Fixed in v2.03
