### ISSUE TITLE
cmd not working

### ISSUE THREAD

**Issue by ahmednore** [Jax-Core/YourFlyouts#11]
when i put this

**Comment by ahmednore** [comment]
iwr -useb "https://raw.githubusercontent.com/Jax-Core/JaxCore/master/CoreInstaller.ps1" | iex

it doesnt work

**Comment by ahmednore** [comment]
help

**Comment by EnhancedJax** [comment]
Please send what it shows in the PowerShell prompt

**Comment by ahmednore** [comment]
![image](https://user-images.githubusercontent.com/80589631/188331586-78a265e4-8004-4771-b6f7-65a7ddc6fe46.png)

**Comment by EnhancedJax** [comment]
Try https://JaxCore.app/

**Comment by ahmednore** [comment]
> Try https://JaxCore.app/
I tried it but it doesn't work 
![image](https://user-images.githubusercontent.com/80589631/188488702-a4c26f5b-5417-4a1f-981d-66c33f6ea442.png)

**Comment by EnhancedJax** [comment]
Your anti-virus might have deleted the file, or it was something else.
Safety FAQs: https://wiki.jaxcore.app/getting-started/faqs/anti-virus-false-positive-faqs

Alternatively, try running the regular powershell as admin (not x86) and run the command again
