### ISSUE TITLE
Can´t install new skins on Rainmeter

### ISSUE THREAD

**Issue by dperabeles** [Jax-Core/YourFlyouts#12]
After installing JaxCore, I can´t install new skins on rainmeter because it will ask me again to install JaxCore. How do I solve this ? Or how do I uninstall JaxCore directly from PowerShell. Already uninstalled Rainmeter and installed it again and have the same problem.

**Comment by EnhancedJax** [comment]
New skins from Rainmeter? If they are not affiliated with JaxCore, it won't prompt you to install JaxCore.
