### ISSUE TITLE
I can't set the keyboard shortcut to change the brightness

### ISSUE THREAD

**Issue by chomichau** [Jax-Core/YourFlyouts#13]
Hello. In the settings, you cannot set the brightness increase /decrease to a combination with the Fn key that is on the laptop keyboard. With its help, the brightness of the system itself changes, namely with a combination of Fn + F2 and Fn + F3. Tell me how to set this combination in YourFlyouts. Thanks.

**Comment by EnhancedJax** [comment]
You cannot remap function keys unfortunately. They work on the hardware level.

**Comment by chomichau** [comment]
But why do Fn+F6/F7/F8 combinations that change the volume work in YourFlyouts? In addition, there are no problems with changing the brightness in the ModernFlyouts application

**Comment by EnhancedJax** [comment]
Turn off `JaxCore -> YourFlyouts -> General -> Setting: Use legacy force brightness changer (Non built-in keys)`, unless you're on Windows 22H2.
