### ISSUE TITLE
Rainmeter/YourFlyouts crashes when launching music player

### ISSUE THREAD

**Issue by chorong761** [Jax-Core/YourFlyouts#14]
[Music Player](https://www.microsoft.com/ko-kr/p/%EB%B2%85%EC%8A%A4-%ED%94%8C%EB%A0%88%EC%9D%B4%EC%96%B4/9wzdncrfj002#activetab=pivot:overviewtab) I'm using, it is not region locked and could be installed from the ms store. 

If I have YourFlyouts enabled, it would crash when I launch that music player. Launching the music player first and then enabling YourFlyouts afterwards would be fine. 

Also another issue is the artist name showing as "0" in the flyout.

Win 11 22H2
YourFlyouts 2.04

**Comment by EnhancedJax** [comment]
Install the beta patch by running this file and unchecking the "Skin" part. The player should function after that. Let me know if you have any other issues.

https://cdn.discordapp.com/attachments/1021535376143306752/1021821360961491004/WindowsNowPlayingExample_1.0.0.4.rmskin

**Comment by chorong761** [comment]
> Install the beta patch by running this file and unchecking the "Skin" part. The player should function after that. Let me know if you have any other issues.
> 
> https://cdn.discordapp.com/attachments/1021535376143306752/1021821360961491004/WindowsNowPlayingExample_1.0.0.4.rmskin

Hi, I've installed the patch and it would still crash when I launch the player

**Comment by EnhancedJax** [comment]
![image](https://user-images.githubusercontent.com/80020581/194680330-9043d07d-f773-45ca-a091-e6a52f9c78ea.png)

Can you send this screen, which can be found at Rainmeter --> Logs --> Version?

**Comment by chorong761** [comment]
![image](https://user-images.githubusercontent.com/17227895/194684964-ecb27916-fb86-418b-82a6-585d6785aacf.png)

**Comment by EnhancedJax** [comment]
The patch should cover this issue, make sure you've unchecked the skins checkbox and not the plugin one. If you're uncertain, run the rmskin file again and install without modification of the checkbox options

**Comment by chorong761** [comment]
![image](https://user-images.githubusercontent.com/17227895/194685470-8f9cf4df-e357-42af-911a-4e3364106ed7.png)
This is what I get when running it again. When I ran it the first time, both boxes were checked and I unchecked the Skins

**Comment by EnhancedJax** [comment]
I guess it's a problem with compatibility then. Switch the media method setting to Auto and it should not crash anymore

**Comment by chorong761** [comment]
> I guess it's a problem with compatibility then. Switch the media method setting to Auto and it should not crash anymore

That solved the crashing problem but broke the media display :( (only shows the volume control now)

**Comment by EnhancedJax** [comment]
Auto mode only supports a limited amount of players, which you can find on the wiki.
