### ISSUE TITLE
My antivirus screamed after i ran this.

### ISSUE THREAD

**Issue by siliconfire** [Jax-Core/YourFlyouts#16]
yes, Kaspersky found "Trojan" on jaxcore. can owners double-check that the website is not hacked or something like that?

also, your website is jaxcore.app right? Please let me know if I am wrong.

**Comment by unholypersona** [comment]
> yes, Kaspersky found "Trojan" on jaxcore. can owners double-check that the website is not hacked or something like that?
> 
> also, your website is jaxcore.app right? Please let me know if I am wrong.

hi, yes jaxcore.app is the correct website and no it's not hacked it's most likely an false positive from your antivirus

**Comment by siliconfire** [comment]
this was me being dumb in 2023

**Comment by chatgptt565656** [comment]
when i run it i got the same idk why but i allow it to make my desktop cool
