### ISSUE TITLE
Just a request

### ISSUE THREAD

**Issue by Meet6656** [Jax-Core/YourFlyouts#2]
I don't know if this is the right place to put a request but in YourFlyouts, can you make it so it can take function keys as hotkeys for brightness controls because i have a laptop and on it , you change brightness with F4 and F5 and it show the default windows flyout . ![Screenshot (35)](https://user-images.githubusercontent.com/61152744/177292868-d60fb485-6c26-40dc-9e61-b5d3d394cb18.png)
And so, I would like a little consistency, 
![Screenshot (36)](https://user-images.githubusercontent.com/61152744/177292875-7cfeed9e-72e4-46b4-bf44-a9834c87a3bd.png)
so please let me remap function keys as hotkeys.

**Comment by EnhancedJax** [comment]
YourFlyouts v2 will now support brightness keys.
