### ISSUE TITLE
Does not support Windows Wheel Volume Control

### ISSUE THREAD

**Issue by thewan056** [Jax-Core/YourFlyouts#3]
When using a Dial device, such as the Surface Dial, that uses the Wheel function in Windows, it does not activate YourFlyouts. It uses the default Windows flyout instead. I encountered this problem first with ModernFlyouts and they have fixed the issue. But I would like to migrate to your Flyout as it looks and feels way better. 

ModernFlyouts-Community/ModernFlyouts#577

**Comment by Skyyblaze** [comment]
I think I have the same problem. I'm using a Logitech G815 keyboard and YourFlyouts v1 worked fine with its volume-wheel. For YourFlyouts v2 I have to use the Legacy setting to make it work or else the default Win11 flyout shows.

**Comment by EnhancedJax** [comment]
> When using a Dial device, such as the Surface Dial, that uses the Wheel function in Windows, it does not activate YourFlyouts. It uses the default Windows flyout instead. I encountered this problem first with ModernFlyouts and they have fixed the issue. But I would like to migrate to your Flyout as it looks and feels way better.

Try enabling `JaxCore -> YourFlyouts -> General -> Setting: Use legacy volume key hooks` and see if it works

**Comment by EnhancedJax** [comment]
> I think I have the same problem. I'm using a Logitech G815 keyboard and YourFlyouts v1 worked fine with its volume-wheel. For YourFlyouts v2 I have to use the Legacy setting to make it work or else the default Win11 flyout shows.

This seems to be unrelated to the original issue. If you are using the insider version of Windows 11, you need the legacy options turned on (Turns on automatically by Core when going through the welcome screen of Flyouts)

**Comment by thewan056** [comment]
My apologies, I just found some time to test this out. It does seem to be working now. Your Flyouts does appear when I use my wheel, but it is not responsive. It sometimes takes a long time to appear, sometimes nearly instantly. And when it appears the volume doesn't smoothly change, it jumps around, like say from 30 to 52 to 76. The increments are kinda random depending how much I turn my wheel.

It might be my PC being too slow. I'm currently using an really old system (around 10+ years old), but I am aiming to change it soon, hopefully by the end of the year. So if it is a performance issue, I don't think we can do much about that.
