### ISSUE TITLE
music player loads for 1 nanoseconds like a blink and then is not visible running on win 11 

### ISSUE THREAD

**Issue by MdAliAhnaf** [Jax-Core/YourFlyouts#4]
![Desktop Screenshot 2022 07 28 - 14 32 40 61](https://user-images.githubusercontent.com/66354256/181460165-cf219ed5-5ae8-4376-a452-b5d21950f5ac.png)

the module is loaded but it is no visible in the screen. A blink of the music player appears for 1 nano second after unloading and reloading again. Same problem just blinks cannot drag no visibility of the music player in yourflyouts!

**Comment by EnhancedJax** [comment]
Please make sure you understand what YourFlyouts does. [README](https://github.com/Jax-Core/YourFlyouts#about)
