### ISSUE TITLE
Support for Capslock+.ahk

### ISSUE THREAD

**Issue by PhoenixCODE2322** [Jax-Core/YourFlyouts#6]
This is script use to ezz the typing manipulation.  [Capslock+](https://github.com/wo52616111/capslock-plus)

This script uses Capslock hold to trigger itself and in a way manipulating some usecase of capslock. like this - 

1. Capslock presss and release quickly -- normal function of capslock -- toggles on / off
2. Capslocak hold for more than a value .. the normal function blocks and capslock will / won't turn on or off and further addition of keys will perform actions.

Now the problem is when capslock is holded .. YourFlyout detect is as On/ Off action of Capslock but capslock+ cancels these action and returning in a false information .
Also as i use this a lot while using VScode ( i see you use vscode - chekout this capslock+ is really cool)  so it results in alot of notification which is false .

**Comment by EnhancedJax** [comment]
CapsLocks+ works fine with YourFlyouts. Try turning off `JaxCore -> YourFlyouts -> General -> Setting: Use locks key hooks`

**Comment by PhoenixCODE2322** [comment]
> CapsLocks+ works fine with YourFlyouts. Try turning off `JaxCore -> YourFlyouts -> General -> Setting: Use locks key hooks`

i tried it .. it was already off .. then i  tried it turning on and see that ... when its on .i am not able to use capslock+ ... so i truned it off.

but my problem is different .. 
here's the step to reproduce and the results of that.

Two scenarios --

- First One ->

1. Press and release capslock instantaneously --- YourFlyouts works perfectly (displays status of Capslock ).

-Second One ->

1. Make sure capslock is off
2. Press Capslock and hold it for 2 second and don't release
3. YourFlyouts shows up and displays that capslock is one.
4. Now because Caplock is still in press and hold position.
5. When you release the capslock now .. it won't be on because Caplock+.ahk has a function where if capslock if holded for a certain duration it will disregard its capslock turning on/off functionality.

Now the thing is When ever capslock is on hold position YourFlyouts pops up saying its on / off but in reality caplock + has disabled the capslock functionality of turninng on/off because it was holded . 

This results in fake pop up .and many pop up because everytime i hold capslock key , youflyout pops up.

**Comment by EnhancedJax** [comment]
I am unable to produce the second scenario... what I did was download the source code and ran capslock+.ahk with AHK stable version installed as admin. If you're comfortable with what you had before, you can turn `JaxCore -> YourFlyouts -> General -> Setting: Enable CapsLock / NumLock / ScrollLock Flyouts` off so it won't display wrong information, however if you know the Autohotkey language, you can add `Run "%RainmeterPath% "!CommandMeasure "Func" "actionLoad('locks')" "YourFlyouts\Main" "` to the part where the Lock state is toggled in the CapsLock+ script.

**Comment by PhoenixCODE2322** [comment]
> 
i don't know both currently.
Sorry one last attempt please .. i will improbe the steps and the result which i forgot to mention in last .

Caplock+.ahk should be running in background with admin rights. To verify .. A tray icon is created.

1.Make sure capsloock current state is off.
2.Press and hold CapsLock for 3 seconds then release . -- YourFlyout Menu pops up saying `Toggled Capslock On`
3.Now try typing somewhere as according to YourFlyout `Capslock is ON`.
4. Observation -- the letters typed will be in small letter not in capital letter.
5. Why because Caplock+.ahk uses Capslock hold as its activation argument. So after Capslock+ is done with. It disregards the turning capslock `ON/OFF` because it will be hassle that everytime you went to use Caplock+.ahk by holding Caplock and you end up with changing Capslock to `ON/OFF` and you will have to again `toggle it` because you did not wanted to trun `ON/OFF` capslock but use Capslock+.ahk functionality

**Comment by PhoenixCODE2322** [comment]
Lol gave it a try. 

> However, if you know the Autohotkey language, you can add `Run "%RainmeterPath% "!CommandMeasure "Func" "actionLoad('locks')" "YourFlyouts\Main" "` to the part where the Lock state is toggled in the CapsLock+ script. Make sure to set the `%RainmeterPath%` variable in AHK.

and worked i was confuse where to add this code .. i found a part where was if else .. tried putting it in `else` first and it worked.

Still... is it still feasible to do from the side of YourFlyout. 
Also it looks like you do not use Capslock+.ahk. Have you never heard of it or tried it .
Or you use Some better alternative ? please let me know

**Comment by EnhancedJax** [comment]
I don't think I will look into this issue further since the fix is simple enough on the user-side and it isn't part of the regular functions. YourFlyouts just displays what is happening, so it wouldn't be reasonable to add a behavior for that, sorry.

> Also it looks like you do not use Capslock+.ahk. Have you never heard of it or tried it .
Or you use Some better alternative ? please let me know

I don't really need an additional modifier key or use caplocks as a whole, so there isn't really a reason to use it

**Comment by PhoenixCODE2322** [comment]
>However, if you know the Autohotkey language, you can add Run "%RainmeterPath% "!CommandMeasure "Func" "actionLoad('locks')" "YourFlyouts\Main" " to the part where the Lock state is toggled in the CapsLock+ script. Make sure to set the %RainmeterPath% variable in AHK.

Ok .. after restarting my system .. it stopped working again..

Then i was able to figure out this was because .. Capslock+.ahk starts before rainmeter and in your case its opposite as you start capslock+.ahk after rainmter. 

i will just delay the capslock.ahk startup

**Comment by EnhancedJax** [comment]
Don't think the load order really matter, but regardless that would be an issue on the script's side. 

I'll close the issue for now, you can re-open it if you want to publish the fix. Thanks
