### ISSUE TITLE
Support For TouchPad Gesture Volume 

### ISSUE THREAD

**Issue by PhoenixCODE2322** [Jax-Core/YourFlyouts#7]
I have set my four-finger Swipe Up or Down to Change Volume. YourFlyout cannot react to the same way (windows does) and the volume increase/decrease animation jumps from one position to another . It is not smooth.

**Comment by EnhancedJax** [comment]
It should be a smooth transition if Windows is able to detect the volume change. Either way, try turning on `JaxCore -> YourFlyouts -> General -> Setting: Use legacy volume key hooks`
