### ISSUE TITLE
YourFlyouts right-click menu flickers back and forth until timeout

### ISSUE THREAD

**Issue by Aegim** [Jax-Core/YourFlyouts#9]
![Screenshot (4474)](https://user-images.githubusercontent.com/111807698/187105004-3b52aa38-f9f5-4a7b-9796-23e471a10eb6.png)
![Screenshot (4475)](https://user-images.githubusercontent.com/111807698/187105005-40dcc2db-a7bc-4d90-933a-5eb7da9633ef.png)

**Comment by EnhancedJax** [comment]
This is a known issue, since the flyouts wants to stay on top and so does the context menu. I dont plan to fix this for now. Thanks for reporting regardless!
